title: Jon Goundry
logo: /assets/img/Selfie.jpg
description: Unearthing digital sands for the gold within.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
  style: compressed
